name: k6 performance tests

on:
  push:
    branches: [ main, developer ]
  pull_request:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install k6 via snap
        run: |
          sudo snap install k6
          k6 version

      - name: Run k6 tests
        run: |
          k6 run script.js
